### NUMPY EXERCISES###

**Exercise 1**

In [21]:
def inner_prod(x,y):
    parz=0
    if len(x)!=len(y):
        
        raise Exception("ERROR DIFFEERENT LENGHTS IN THE VECTORS")
        
    else:
        for i in range(len(x)):
            parz+=x[i]*y[i]
      
    return parz


##versione più compatta utilizzando numpy, ha però bisogno dei numpy array
import numpy as np

def inner_prod2(x,y):
    
    if len(x)!=len(y):
        
        raise Exception("ERROR DIFFEERENT LENGHTS IN THE VECTORS")
    else:
        return np.sum((x*y))
    



In [22]:
x=np.r_[1,2,3,3]
y=np.r_[1,2,4,4]
print(inner_prod(x,y))
print(x*y)
print(inner_prod2(x,y))

29
[ 1  4 12 12]
29


In [14]:
x=[1,2,3,3]
y=[1,2,4,4,5]

inner_prod(x,y)

Exception: ERROR DIFFEERENT LENGHTS IN THE VECTORS

**Exercise 2**

In [24]:
import numpy as np
import math

def mean_abs_err(x,y):
    parz=0
    if len(x)!=len(y):
        
        raise Exception("ERROR DIFFEERENT LENGHTS IN THE VECTORS")
        
    else:
        for i in range(len(x)):
            parz+=math.fabs(y[i]-x[i])
    return parz/len(x) 


##anche qua puoi fare la versione utilizzando numpy 

def mean_abs_err2(x,y):
    if len(x)!=len(y):
        raise Exception ("ERROR DIFFERENT LENGHTS IN THE VECTORS")
    else:
        return np.sum(abs(y-x))/len(x)
    
    
    

In [25]:
x=np.array([1,2,3])
y=np.array([2,3,4])

print(mean_abs_err(x,y))
print(mean_abs_err2(x,y))

1.0
1.0


In [68]:
x=np.array([1,2,3,5])
y=np.array([2,3,4])

mean_abs_err(x,y)

Exception: ERROR DIFFEERENT LENGHTS IN THE VECTORS

**Exercise 3, part A**

In [46]:
def lead(x,n):
    if n>len(x):
        
        raise Exception("I CANNOT TAKE OUT A NUMBER OF ELEMENTS GREATER THAN THE NUMBER OF ELEMENTS IN THE VECTOR")
    else:
        for i in range(len(x)-n,len(x)):
            x[i]=math.nan
            
        
    return x

In [69]:
x = np.r_[2., 3., 4., 5., 6]
print(x)

[2. 3. 4. 5. 6.]


In [70]:
lead(x, 2)

array([ 2.,  3.,  4., nan, nan])

In [72]:
r = np.r_[2.,3.,4.]
print(r)

[2. 3. 4.]


In [73]:
lead(r, 5)

Exception: I CANNOT TAKE OUT A NUMBER OF ELEMENTS GREATER THAN THE NUMBER OF ELEMENTS IN THE VECTOR

**Exercise 3, part B**

In [55]:
def lag(x,n):
    if n>len(x):
        
        raise Exception("I CANNOT TAKE OUT A NUMBER OF ELEMENTS GREATER THAN THE NUMBER OF ELEMENTS IN THE VECTOR")
    else:
        for i in range(0, n):    
            x[i]=math.nan
            
        
    return x

In [74]:
q = np.r_[2.,3.,4., 5., 6]
print(q)

[2. 3. 4. 5. 6.]


In [75]:
lag(q, 2)

array([nan, nan,  4.,  5.,  6.])

In [78]:
b = np.r_[6., 7., 8.]
print(b)

[6. 7. 8.]


In [79]:
lag(b, 5)

Exception: I CANNOT TAKE OUT A NUMBER OF ELEMENTS GREATER THAN THE NUMBER OF ELEMENTS IN THE VECTOR

**Exercise 4**

In [62]:
def distanza(A,y):
    if A.shape[1] != len(y):
        raise Exception("THE MATRIX AND THE VECTOR ARE NOT COMPARABLE")
    else:
        parz = np.zeros(A.shape[0])
        
        for i in range(A.shape[0]):
            
            for j in range(len(y)):
              
                parz[i]+=(A[i,j]-y[j])**2
        
        return parz
    
    
    
##versione numpy 

def distanza2(A,y):
    if A.shape[1]!=len(y):
        raise Exception("the matrix and the vector are not comprable")
    else:
        parz=np.zeros(A.shape[0])
        for i in range(A.shape[0]):
            parz[i]=np.sum((A[i,:]-y)**2)
    return parz


     
            


In [48]:
A = np.c_[[1.,2.,4.],[3.4,5.6,13.2],[2.1,2.2,3.3],[5.5,6.7,7.6]]
print(A)

[[ 1.   3.4  2.1  5.5]
 [ 2.   5.6  2.2  6.7]
 [ 4.  13.2  3.3  7.6]]


In [49]:
y = np.r_[(2.3, 4.3, 7.67,5.45)]
print(y)
A.shape[1]

[2.3  4.3  7.67 5.45]


4

In [50]:
distanza(A,y)

array([ 33.5274,  33.2634, 105.8194])

In [63]:
distanza2(A,y)

array([ 33.5274,  33.2634, 105.8194])